kind: Service
apiVersion: v1
metadata:
 name: windows-exporter
 namespace: monitoring
 labels:
   app: windows-exporter
   release: prometheus
spec:
 type: ClusterIP
 ports:
 - name: metrics
   port: 9182
   targetPort: 9182
---
kind: Endpoints
apiVersion: v1
metadata:
 name: windows-exporter
 namespace: monitoring
 labels:
   app: windows-exporter
   release: prometheus
subsets:
 - addresses:
     #This is an external address
     - ip: 192.168.1.37
   ports: 
     - name: metrics
       port: 9182
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: windows-exporter
    release: prometheus
  name: windows-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  # Take care here
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: windows-exporter
      release: prometheus

