apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: windows-exporter
    release: prometheus
  name: windows-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  # Take care here
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: windows-exporter
      release: prometheus