controller:
  image:
    repository: k8s.gcr.io/ingress-nginx/controller
    tag: "v0.41.2"
    digest: ""
    pullPolicy: IfNotPresent
    runAsUser: 101
    allowPrivilegeEscalation: true

  config:

  # Required for host port management otherwise the new pod stay in pending state
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  # Optionally change this to ClusterFirstWithHostNet in case you have 'hostNetwork: true'.
  # By default, while using host network, name resolution uses the host's DNS. If you wish nginx-controller
  # to keep resolving names inside the k8s network, use ClusterFirstWithHostNet.
  dnsPolicy: ClusterFirstWithHostNet


  #reportNodeInternalIp: true

  # Required for use with CNI based kubernetes installations (such as ones set up by kubeadm),
  # since CNI and hostport don't mix yet. Can be deprecated once https://github.com/kubernetes/kubernetes/issues/23920
  # is merged
  hostNetwork: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  replicaCount: 1

  publishService:
    enabled: false

  extraArgs:
    default-ssl-certificate: "$(POD_NAMESPACE)/shared-tls"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key:  kast/ingress-nginx
            operator: In
            values:
              - enabled
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - ingress-nginx
          - key: app.kubernetes.io/component
            operator: In
            values:
            - controller
        topologyKey: "kubernetes.io/hostname"

  service:
    enabled: false
    type: ClusterIP

  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      image:
        repository: docker.io/jettech/kube-webhook-certgen
        tag: v1.5.0
        pullPolicy: IfNotPresent

defaultBackend:
  enabled: False
  image:
    repository: k8s.gcr.io/defaultbackend-amd64
    tag: "1.5"
