{{- if .Values.ingressStudio.enabled -}}
{{- $fullName := include "warp10-demo.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-studio
  labels:
    {{- include "warp10-demo.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  {{- if .Values.ingressStudio.tls }}
  tls:
    {{- range .Values.ingressStudio.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingressStudio.path }}(/|$)(.*)
            backend:
              serviceName: {{ $fullName }}-studio
              servicePort: {{ $svcPort }}
  {{- end }}
