apiVersion: v1
kind: Service
metadata:
  name: {{ include "warp10-demo.fullname" . }}-studio
  labels:
    {{- include "warp10-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "warp10-demo.selectorLabels" . | nindent 4 }}
